version: "3"

services:
  iptv-magiogo:
    image: ghcr.io/xhyrom/iptv-magiogo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "4589:4589"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      MAGIO_USERNAME: ${MAGIO_USERNAME}
      MAGIO_PASSWORD: ${MAGIO_PASSWORD}
      HOST: ${HOST}
