name: Push image to ghcr.io

on:
  push:

permissions: write-all

jobs:
  push:
    name: "Build Docker"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get short SHA for tag
        uses: 2428392/gh-truncate-string-action@v1
        id: truncatedString
        with:
          stringToTruncate: ${{ github.sha }}
          maxLength: 7
      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/xhyrom/iptv-magiogo:latest
            ghcr.io/xhyrom/iptv-magiogo:${{ steps.truncatedString.outputs.string }}
